# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 32c09a9440bd6f60530c1591119cf03ff15e12478ebb486264098be6fe1880e4a745d501c4766a3a183a8c267fbc65fbf38058d72433f03576807c12f3348d33

test:
  secret_key_base: 1a9098dd0bc64950b53b9dce42d73dad2fb35043b5a4054391bb49ca838eea55dbd2e622f8f8656ef1fb2220a724d19e2b2cbf1e1136052660cb4d0197ff798f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
